from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any

class CrawlRequest(BaseModel):
    url: str = Field(..., description="The base URL of the website to crawl.")
    max_pages: int = Field(default=10, description="The maximum number of pages to crawl.")
    max_depth: int = Field(default=2, description="The maximum crawl depth relative to the base URL.")

class CrawlResponse(BaseModel):
    job_id: str = Field(..., description="Unique ID for the background crawl job.")
    status: str = Field(..., description="Current status of the crawl job.")

class CrawlStatusResponse(BaseModel):
    job_id: str
    status: str
    progress: float = Field(..., description="Percentage completion from 0 to 100.")
    crawled_count: int = Field(..., description="Number of successfully crawled and parsed pages.")
    crawled_pages: List[str] = Field(default_factory=list, description="List of crawled page URLs.")
    errors: List[str] = Field(default_factory=list, description="List of errors encountered during crawl.")

class Message(BaseModel):
    role: str = Field(..., description="Either 'user' or 'assistant'.")
    content: str = Field(..., description="Text content of the message.")

class ChatRequest(BaseModel):
    query: str = Field(..., description="The user's query.")
    website_url: Optional[str] = Field(default=None, description="The website domain/URL to query. If None, queries all websites.")
    chat_history: List[Message] = Field(default_factory=list, description="Conversation history for context.")
    model_override: Optional[str] = Field(default=None, description="Allow choosing a specific Gemini model.")

class Citation(BaseModel):
    source: str = Field(..., description="URL source of the chunk.")
    title: str = Field(..., description="Page title.")
    content_type: str = Field(..., description="Content type (e.g. text, table, pdf).")
    score: float = Field(..., description="Similarity score.")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="The context-augmented answer generated by the model.")
    sources: List[Citation] = Field(default_factory=list, description="Citations used in generating the answer.")

class WebsiteItem(BaseModel):
    url: str
    title: str
    pages_count: int
